#pragma config(Sensor, dgtl4,  sonarRight,     sensorSONAR_cm)
#pragma config(Sensor, dgtl6,  sonarLeft,      sensorSONAR_cm)
#pragma config(Sensor, dgtl8,  sonarBack,      sensorSONAR_cm)
#pragma config(Sensor, dgtl10, sonarFront,     sensorSONAR_cm)
#pragma config(Motor,  port2,  frontRight,    tmotorNormal, openLoop)
#pragma config(Motor,  port3,  backRight,     tmotorNormal, openLoop)
#pragma config(Motor,  port4,  frontLeft,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port5,  backLeft,      tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                 - Forward until Close Proximity -                                  *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs the robot to drive forward at half speed until the Ultrasonic Sensor       *|
|*  detects an obstruction within 20 inches of it.                                                    *|
|*  There is a two second pause at the beginning of the program.                                      *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Digital - Port 9,10 sonarSensor         VEX Sonar Sensor      Front mounted, facing forward     *|
|*    UART Port 2         none                VEX LCD               VEX LCD Screen                    *|
\*-----------------------------------------------------------------------------------------------4246-*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{

	while(true){

		motor[frontRight] = vexRT[Ch3] - vexRT[Ch1] - vexRT[Ch4];
    motor[backRight] =  vexRT[Ch3] - vexRT[Ch1] + vexRT[Ch4];
    motor[frontLeft] = vexRT[Ch3] + vexRT[Ch1] + vexRT[Ch4];
    motor[backLeft] =  vexRT[Ch3] + vexRT[Ch1] - vexRT[Ch4];

		wait1Msec(1000);
		clearLCDLine(0);                      // Clear line 1 (0) of the LCD
  	clearLCDLine(1);                      // Clear line 2 (1) of the LCD

 	 	bLCDBacklight = true;                 // Turn on LCD Backlight

  	displayLCDPos(0,0);
  	displayNextLCDString("F:");
 		displayNextLCDNumber(SensorValue(sonarFront));
 		displayNextLCDString("CM");

 		displayLCDPos(0,9);
 		displayNextLCDString("B:");
 		displayNextLCDNumber(SensorValue(sonarBack));
 		displayNextLCDString("CM");

 		displayLCDPos(1,0);
 		displayNextLCDString("L:");
 		displayNextLCDNumber(SensorValue(sonarLeft));
 		displayNextLCDString("CM");

 		displayLCDPos(1,9);
 		displayNextLCDString("R:");
 		displayNextLCDNumber(SensorValue(sonarRight));
 		displayNextLCDString("CM");
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
