#pragma config(Motor,  port2,           leftmotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightmotor,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (1 == 1)
	{
		motor[leftmotor] = (vexRT[Ch2]);
		motor[rightmotor] = (vexRT[Ch3]);

	}

}
