#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(UART_Usage, UART2, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;

int nBatteryAverage = nAvgBatteryLevel;

task main()
{

	string mainBattery, backupBattery;

	while (true) {

		displayLCDString(1, 0, "Bat: ");
		sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V');
		displayNextLCDString(mainBattery);

	  motor[frontRight] = vexRT[Ch3];
	  motor[backLeft] = vexRT[Ch3];
    motor[backRight] = vexRT[Ch2];
    motor[frontLeft] = vexRT[Ch2];

    if(vexRT[Btn8U] == 1)
		{
			bLCDBacklight = true;
		}
		else {
			bLCDBacklight = false;
		}

	}

}
