#pragma config(Motor,  port2,           leftfront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftback,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightfront,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightback,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
		while (true)
		{
			motor[port2] = (vexRT[Ch3]);
			motor[port3] = (vexRT[Ch3]);
			motor[port4] = (vexRT[Ch2]);
			motor[port5] = (vexRT[Ch2]);
		}

}
