#pragma config(Sensor, in1,    expander_1,     sensorAnalog)
#pragma config(Motor,  port2,           driveLeftA,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           driveLeftB,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           driveRightA,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           driveRightB,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           steerLeft,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           steerRight,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

task display_battery()
{
	string mainBattery, backupBattery;
	while (true)
	{
		clearLCDLine(0);											// Clear line 1 (0) of the LCD
		clearLCDLine(1);											// Clear line 2 (1) of the LCD

		//Display the Primary Robot battery voltage
		displayLCDString(0, 0, "Primary: ");
		sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
		displayNextLCDString(mainBattery);

		//Display the Backup battery voltage
		displayLCDString(1, 0, "Expander: ");
		sprintf(backupBattery, "%1.2f%c", SensorValue(expander_1)/283.2, 'V');	//Build the value to be displayed
		displayNextLCDString(backupBattery);

		wait1Msec(100);
	}
}

task main()
{
	bLCDBacklight = true;//lcd backlight
	startTask(display_battery);

	while (true)
	{
		//Gotta go fast!!!!!!!
		motor[driveLeftA]  = (vexRT[Ch3]);//drive
		motor[driveLeftB]  = (vexRT[Ch3]);//drive
		motor[driveRightA] = (vexRT[Ch3]);//drive
		motor[driveRightB] = (vexRT[Ch3]);//drive
		motor[steerLeft]   = (vexRT[Ch1]);//steer
		motor[steerRight]  = (vexRT[Ch1]);//steer
	}
}
