#pragma config(UART_Usage, UART2, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  armRight,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  armLeft,        sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           driveRight,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           driveLeft,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port4,           driveMiddle,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           armRight,      tmotorVex393_HBridge, openLoop, encoder, encoderPort, I2C_1)
#pragma config(Motor,  port6,           armLeft,       tmotorVex393_HBridge, openLoop, encoder, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"


void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

task autonomous()
{

	AutonomousCodePlaceholderForTesting();
}

task usercontrol()
{

	while (true)
	{

		//	if(vexRT[Btn8R] == 1) {
		//			clearLCDLine(0);
		//			clearLCDLine(1);
		//			nMotorEncoder[armRight] = 0;
		//			nMotorEncoder[armLeft] = 0;
		//			displayLCDPos(1,8);
		//			displayNextLCDString("Clear");
		//	}

			//displayLCDPos(0,1);
			//displayNextLCDNumber(SensorValue[armRight]);

		while (motor[driveLeft] != 0 && motor[driveRight] != 0) {
			// Display motor encoder values
			displayLCDNumber(0, 1, nMotorEncoder[armRight]);
			displayLCDNumber(1, 1, nMotorEncoder[armLeft]);
			//Consider removing the wait and clear line code, as it wasen't in the while loop
			//In the example code (Then again, that didn't work either)
			wait1Msec(100);
			clearLCDLine(0);
			clearLCDLine(1);
		}


			motor[driveRight] = (vexRT[Ch2]);
			motor[driveLeft] = (vexRT[Ch3]);
			if(vexRT[Btn5D] == 1) {
				motor[driveMiddle] = -127;
			}
			else if(vexRT[Btn6D] == 1)
			{
				motor[driveMiddle] = 127;
			}
			else if(vexRT[Btn6U] == 1)
			{
				motor[armRight] = 127;
				motor[armLeft] = 127;
			}
			else if(vexRT[Btn5U] == 1)
			{
				motor[armRight] = -127;
				motor[armLeft] = -127;
			}
			else
			{
				motor[armRight] = 0;
				motor[armLeft] = 0;
				motor[driveMiddle] = 0;
			}

	}
}
