#pragma config(UART_Usage, UART2, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  armRight,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  armLeft,        sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           driveRight,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           driveLeft,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port4,           driveMiddle,   tmotorVex393_MC29, openLoop)
//393 Motor IME:	627.2 ticks per revolution of the output shaft.
#pragma config(Motor,  port5,           armRight,      tmotorVex393_HBridge, openLoop, encoder, encoderPort, I2C_1)
#pragma config(Motor,  port6,           armLeft,       tmotorVex393_HBridge, openLoop, encoder, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"

//Current Battery level in millivolts (Value of 10456 means 10.456 Volts)
//Average refers to the fact that the measurements are the average of 20 samples, taken to smooth voltage spikes and drops
//Data type: Short
//Min/max = (-32,768 - +32,767)
int nBatteryAverage = nAvgBatteryLevel;
//Sets armRight to master motor and armLeft to slave motor, thus, input sent to one will be mirrored to the other
slaveMotor(armLeft, armRight);
//Map armRight ro port 5 (???)
mapEncoderToMotor(port5, I2C_1);
//Get motor velocity from armRight
int motorRpm = getMotorVelocity(port5);
//Define wheel diamete, ticks per revolution and ticks per one degree at some point
//Also check arm motor gearing (speed VS torque)

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
  	// resetMotorEncoder(xMotor);
}

task autonomous()
{
	AutonomousCodePlaceholderForTesting();
}

task usercontrol()
{

	while (true)
	{

		//Display battery average
		displayLCDPos(0,1);
		displayNextLCDNumber(nBatteryAverage);
		// or
		displayLCDNumber(0,0,nBatteryAverage);
		// There can be only one
		// Hey, why not try
		//Functional (???)
		displayLCDNumber(nMotorEncoder[armRight]);
		// at some point, eh?

			motor[driveRight] = (vexRT[Ch2]);
			motor[driveLeft] = (vexRT[Ch3]);
			if(vexRT[Btn5D] == 1) {
				motor[driveMiddle] = -127;
			}
			else if(vexRT[Btn6D] == 1)
			{
				motor[driveMiddle] = 127;
			}
			else if(vexRT[Btn6U] == 1)
			{
				motor[armRight] = 127;
				motor[armLeft] = 127;
			}
			else if(vexRT[Btn5U] == 1)
			{
				motor[armRight] = -127;
				motor[armLeft] = -127;
			}
			else
			{
				motor[armRight] = 0;
				motor[armLeft] = 0;
				motor[driveMiddle] = 0;
			}

	}
} //Close user control
