#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while (true) {

	  motor[frontRight] = vexRT[Ch3];
	  motor[backLeft] = vexRT[Ch3];
    motor[backRight] = vexRT[Ch2];
    motor[frontLeft] = vexRT[Ch2];

	}

}
