#pragma config(Motor,  port2,           rightMotorf,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           rightMotorb,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           leftMotorf,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           leftMotorb,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           armMotorRT,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           armMotorRB,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           clawMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           armMotorsL,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//None of the directions are correct
//There are no comments
//No pushbar control
//---Good luck---


task main(){
  while(1 == 1){
    motor[leftMotorf] = -vexRT[Ch2] / 2;
    motor[leftMotorb] = -vexRT[Ch2] / 2;
    motor[rightMotorf] = vexRT[Ch3] / 2;
		motor[rightMotorb] = vexRT[Ch3] / 2;

		//Right side top button
		if(vexRT[Btn8D] == 1){
      motor[armMotorRT] = -128;
      motor[armMotorRB] = -128;
      motor[armMotorsL] = -256;
    }
    else if(vexRT[Btn8U] == 1){
      motor[armMotorRT] = 128;
      motor[armMotorRB] = 128;
      motor[armMotorsL] = 256;
    }
    else if(vexRT[Btn8L] == 1){
    	motor[clawMotor] = -10;
  	}
  	else if(vexRT[Btn8R] == 1){
    	motor[clawMotor] = 10;
  	}
    else{ //If no puttons are pressed, set motors to 0 turning speed, thus becoming limp.
      motor[armMotorRT] = 0;
      motor[armMotorRB] = 0;
      motor[clawMotor] = 0;
      motor[armMotorsL] = 0;
    }
  }
}
