#pragma config(Motor,  port2,           frontRight,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           backRight,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           frontLeft,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
	motor[frontRight] = -vexRT[Ch2];
	motor[backRight] = -vexRT[Ch2];

	motor[frontLeft] = vexRT[Ch3];
	motor[backLeft] = vexRT[Ch3];
	}
}
